import sqlite3
from sqlite3 import Error

dbname = 'pythonsqlite.db'

conn = sqlite3.connect(db_file)
